import type { CourseDoc } from '@/types/firebase'

export const DEFAULT_ALFREDO_COURSES: (CourseDoc & { id: string })[] = [
  {
    id: 'lesson-1',
    instructorId: 'instructor_alfredo',
    instructorName: 'Engineer Alfredo',
    categoryId: 'programming-ai',
    categoryName: 'Programming & AI',
    title: 'Lesson 1: Foundations',
    titleAr: 'الحصة 1: أساسيات البرمجة والذكاء الاصطناعي',
    description: 'Foundations of programming, computational thinking, algorithms, and introducing AI concepts.',
    descriptionAr: 'تأسيس قوي في التفكير البرمجي، المفاهيم الأساسية للخوارزميات ومقدمة في عالم الذكاء الاصطناعي.',
    thumbnailUrl: '/images/courses/lesson-1.jpg',
    status: 'published',
    price: 120,
    currency: 'EGP',
    level: 'beginner',
    language: 'both',
    durationMinutes: 120,
    lessonsCount: 1,
    studentsCount: 38,
    rating: 5.0,
    ratingsCount: 24,
    isFeatured: true,
    certificateEnabled: true,
    maxDevices: 2,
    watchAttempts: 10,
    requiresActivation: false,
    isPackage: false,
    liveSchedule: 'كل يوم أربعاء الساعة 6:00 مساءً',
    liveScheduleAr: 'كل يوم أربعاء الساعة 6:00 مساءً',
    nextLiveDate: '2026-09-23T18:00:00',
    searchKeywords: ['programming', 'ai', 'lesson 1', 'foundations', 'برمجة', 'ذكاء اصطناعي'],
    createdAt: new Date('2026-09-01'),
    updatedAt: new Date('2026-09-18'),
  },
  {
    id: 'lesson-2',
    instructorId: 'instructor_alfredo',
    instructorName: 'Engineer Alfredo',
    categoryId: 'programming-ai',
    categoryName: 'Programming & AI',
    title: 'Lesson 2: Practice',
    titleAr: 'الحصة 2: التطبيق والممارسة البرمجية',
    description: 'Hands-on practice, coding structures, solving real problems, and debugging.',
    descriptionAr: 'تطبيق عملي مكثف، هياكل البيانات، حل المشكلات البرمجية والتصحيح خطوة بخطوة.',
    thumbnailUrl: '/images/courses/lesson-2.jpg',
    status: 'published',
    price: 120,
    currency: 'EGP',
    level: 'beginner',
    language: 'both',
    durationMinutes: 120,
    lessonsCount: 1,
    studentsCount: 35,
    rating: 5.0,
    ratingsCount: 19,
    isFeatured: true,
    certificateEnabled: true,
    maxDevices: 2,
    watchAttempts: 10,
    requiresActivation: false,
    isPackage: false,
    liveSchedule: 'كل يوم أربعاء الساعة 6:00 مساءً',
    liveScheduleAr: 'كل يوم أربعاء الساعة 6:00 مساءً',
    nextLiveDate: '2026-09-23T18:00:00',
    searchKeywords: ['programming', 'ai', 'lesson 2', 'practice', 'برمجة', 'تطبيق'],
    createdAt: new Date('2026-09-01'),
    updatedAt: new Date('2026-09-18'),
  },
  {
    id: 'lesson-3',
    instructorId: 'instructor_alfredo',
    instructorName: 'Engineer Alfredo',
    categoryId: 'programming-ai',
    categoryName: 'Programming & AI',
    title: 'Lesson 3: Projects',
    titleAr: 'الحصة 3: بناء المشاريع الحقيقية',
    description: 'End-to-end practical project development, architectures, and implementation.',
    descriptionAr: 'بناء مشاريع برمجية متكاملة وتطبيقات عملية تربط كافة المفاهيم ببعضها.',
    thumbnailUrl: '/images/courses/lesson-3.jpg',
    status: 'published',
    price: 120,
    currency: 'EGP',
    level: 'beginner',
    language: 'both',
    durationMinutes: 120,
    lessonsCount: 1,
    studentsCount: 32,
    rating: 5.0,
    ratingsCount: 22,
    isFeatured: true,
    certificateEnabled: true,
    maxDevices: 2,
    watchAttempts: 10,
    requiresActivation: false,
    isPackage: false,
    liveSchedule: 'كل يوم أربعاء الساعة 6:00 مساءً',
    liveScheduleAr: 'كل يوم أربعاء الساعة 6:00 مساءً',
    nextLiveDate: '2026-09-23T18:00:00',
    searchKeywords: ['programming', 'ai', 'lesson 3', 'projects', 'برمجة', 'مشاريع'],
    createdAt: new Date('2026-09-01'),
    updatedAt: new Date('2026-09-18'),
  },
  {
    id: 'lesson-4',
    instructorId: 'instructor_alfredo',
    instructorName: 'Engineer Alfredo',
    categoryId: 'programming-ai',
    categoryName: 'Programming & AI',
    title: 'Lesson 4: AI Tools',
    titleAr: 'الحصة 4: أدوات ونماذج الذكاء الاصطناعي',
    description: 'Advanced AI tooling, prompt engineering, LLM integration, and modern tech workflows.',
    descriptionAr: 'التعامل مع أدوات ونماذج الذكاء الاصطناعي الحديثة وهندسة الأوامر وتوظيف الذكاء الاصطناعي.',
    thumbnailUrl: '/images/courses/lesson-4.jpg',
    status: 'published',
    price: 120,
    currency: 'EGP',
    level: 'beginner',
    language: 'both',
    durationMinutes: 120,
    lessonsCount: 1,
    studentsCount: 29,
    rating: 5.0,
    ratingsCount: 28,
    isFeatured: true,
    certificateEnabled: true,
    maxDevices: 2,
    watchAttempts: 10,
    requiresActivation: false,
    isPackage: false,
    liveSchedule: 'كل يوم أربعاء الساعة 6:00 مساءً',
    liveScheduleAr: 'كل يوم أربعاء الساعة 6:00 مساءً',
    nextLiveDate: '2026-09-23T18:00:00',
    searchKeywords: ['programming', 'ai', 'lesson 4', 'ai tools', 'ذكاء اصطناعي'],
    createdAt: new Date('2026-09-01'),
    updatedAt: new Date('2026-09-18'),
  },
  {
    id: 'first-month-package',
    instructorId: 'instructor_alfredo',
    instructorName: 'Engineer Alfredo',
    categoryId: 'programming-ai',
    categoryName: 'Programming & AI',
    title: 'First Month Package (4 Lessons)',
    titleAr: 'باكدج الشهر الأول (4 حصص)',
    description: 'Complete 1st month bundle containing all 4 lessons (Foundations, Practice, Projects, AI Tools) with weekly live sessions every Wednesday at 6:00 PM.',
    descriptionAr: 'الباقة الشاملة للشهر الأول وتضم الـ 4 حصص كاملة (الأساسيات، التطبيق، المشاريع، وأدوات الذكاء الاصطناعي) مع حضور حصص اللايف الأسبوعية كل أربعاء الساعة 6 مساءً وخصم خاص.',
    thumbnailUrl: '/images/courses/first-month-package.jpg',
    status: 'published',
    price: 440,
    currency: 'EGP',
    level: 'beginner',
    language: 'both',
    durationMinutes: 480,
    lessonsCount: 4,
    studentsCount: 52,
    rating: 5.0,
    ratingsCount: 48,
    isFeatured: true,
    certificateEnabled: true,
    maxDevices: 2,
    watchAttempts: 10,
    requiresActivation: false,
    isPackage: true,
    packageCourseIds: ['lesson-1', 'lesson-2', 'lesson-3', 'lesson-4'],
    liveSchedule: 'كل يوم أربعاء الساعة 6:00 مساءً',
    liveScheduleAr: 'كل يوم أربعاء الساعة 6:00 مساءً',
    nextLiveDate: '2026-09-23T18:00:00',
    searchKeywords: ['package', 'first month', 'programming', 'ai', 'باكدج', 'الشهر الأول'],
    createdAt: new Date('2026-09-01'),
    updatedAt: new Date('2026-09-18'),
  },
]
